// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEr_BELXLE2sX2svNzCif95ezPXkdznzk',
    appId: '1:740252476324:web:2dee786209b6f101b1d731',
    messagingSenderId: '740252476324',
    projectId: 'spotfinder-admin',
    authDomain: 'spotfinder-admin.firebaseapp.com',
    storageBucket: 'spotfinder-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb-8-7H9CU-G3laVQVmaM-DajBGHd3Ycc',
    appId: '1:740252476324:android:cfafd8fb2c0667d5b1d731',
    messagingSenderId: '740252476324',
    projectId: 'spotfinder-admin',
    storageBucket: 'spotfinder-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZxyim5qpcH4m2L-kKBrEmx3HEL8PIrk',
    appId: '1:740252476324:ios:b81d8eb958dd13d1b1d731',
    messagingSenderId: '740252476324',
    projectId: 'spotfinder-admin',
    storageBucket: 'spotfinder-admin.appspot.com',
    iosClientId: '740252476324-f62lu7t8q13lu55q6kbkah4bfm8clbc5.apps.googleusercontent.com',
    iosBundleId: 'ch.bungeemonkey.spotfinderAdmin',
  );
}
